### ISSUE TITLE
Distributing all those books for free ... is it legal?

### ISSUE THREAD

**Issue by clawfire** [arpitjindal97/technology_books#5]
I really salute the effort but I question de legality of it. Wouldn't want to harm by spreading the information about this repo too much and cause trouble to the owner.

**Comment by coheneye** [comment]
This is just a probelm about if you're allowed to put books you bought on github, if they should have the power on books after they selling them.

**Comment by Soobrakay** [comment]
> This is just a probelm about if you're allowed to put books you bought on github, if they should have the power on books after they selling them.

That's called [Copyright](https://en.wikipedia.org/wiki/Copyright). If the repository were private and the owner keeping them for backups (e.g., in case of local hard drive failures), that would be one thing and could be considered under Fair Use. Putting them in a public repository with the message encouraging download and distribution is likely piracy unless every book on here is under Creative Commons or some other license that allows redistribution.

**Comment by clawfire** [comment]
That's my concern. If the licence allows it, I would encourage it by spreading the news about the repo. But in the other case, I can't make under my company name public publicity of it :/

**Comment by dssecret** [comment]
Most PDFs that search engines can scrape online are permitted to be scraped by the websites' `robots.txt` and most have a license that allows redistribution.

**Comment by MatthiasWinkelmann** [comment]
I just checked five of the PDFs and every single one includes a copyright notice on the second page. I've reported the repository, and you should probably delete it yourself before you get into trouble with the publishers.
